### PR TITLE
Fixes the cmake-config used during find_package

### PR DESCRIPTION
**Pull request by azeey**
The provided cmake-config was not actually working if one did
```
find_package(gz_cmake_vendor)
find_package(gz-cmake)
```

This because the config file tried to create aliases to targets that don't exist. For example, gz-cmake4::gz-cmake4 is not exported by gz-cmake.

### CODE REVIEW

**Comment by azeey** [comment]
Building upto `rviz2`, but only testing upto gz_cmake_vendor since this mainly affects compile time behavior

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21763/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16036/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1267/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22463/)

**Comment by azeey** [comment]
This is needed for https://github.com/gazebo-release/gz_ogre_next_vendor/pull/6

**Comment by azeey** [comment]
One more try after rebasing #9 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21771/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16043/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1275/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22470/)

**Review by j-rivero — APPROVED** [review]
Changes make sense to me, gz-cmake does not produce any component like the other libs usually do.

**Pull request merged**
